/** @format */

module.exports = {
	// ** AUTHENTICATION LOADING
	LOGIN: 'LOGIN',
	LOGOUT: 'LOGOUT',
	REQUEST_PASSWORD_RESET_TOKEN: 'REQUEST_PASSWORD_RESET_TOKEN',
	VERIFY_PASSWORD_RESET_TOKEN: 'VERIFY_PASSWORD_RESET_TOKEN',
	PASSWORD_RESET: 'PASSWORD_RESET',

	// ** ADMIN PANEL ACTIONS LOADING
	CREATE_ADMIN: 'CREATE_ADMIN',
	EDIT_ADMIN: 'EDIT_ADMIN',
	DELETE_ADMIN: 'DELETE_ADMIN',
};
